version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8.12.0
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: auth-npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build:
    <<: *defaults
    steps:
      - run:
          name: Build
          command: npm run build
  publish:
    <<: *defaults
    steps:
      - run:
          name: Publish
          command: npm run publish
workflows:
  version: 2
  build_and_publish:
    jobs:
      - install:
          context: default
      - build:
          context: default
          requires:
            - install
      - publish:
          context: default
          requires:
            - install
            - build
          filters:
            branches:
              only:
                - master
