version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8.12.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: auth-npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate uuids
          command: npm run uuids
      - run:
          name: Build
          command: npm run build
  publish:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'b9:87:d9:45:8f:fc:7d:af:b2:f9:e0:7a:98:b1:54:b6'
      - run:
          name: auth-npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate uuids
          command: npm run uuids
      - run:
          name: Commit uuids
          command: |
            git add .
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@thinkful.com"
            # don't fail if there's nothing to commit
            git diff-index --quiet HEAD || git commit -m "Automatic commit of uuids after pushing to master [CI skip]"
            git push origin $CIRCLE_BRANCH --force
      - run:
          name: Publish
          command: npm run publish
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          context: default
      - publish:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - preview
